<?php

/**
 * College Sports Management System
 * Comprehensive Sport Registry - 100+ Disciplines
 */

$sport_registry = [
    // Ball & Team Sports
    ['name' => 'Football/Soccer', 'icon' => '⚽', 'type' => 'team'],
    ['name' => 'Basketball', 'icon' => '🏀', 'type' => 'team'],
    ['name' => 'Cricket', 'icon' => '🏏', 'type' => 'team'],
    ['name' => 'Volleyball', 'icon' => '🏐', 'type' => 'team'],
    ['name' => 'Field Hockey', 'icon' => '🏑', 'type' => 'team'],
    ['name' => 'American Football', 'icon' => '🏈', 'type' => 'team'],
    ['name' => 'Rugby Union', 'icon' => '🏉', 'type' => 'team'],
    ['name' => 'Baseball', 'icon' => '⚾', 'type' => 'team'],
    ['name' => 'Softball', 'icon' => '🥎', 'type' => 'team'],
    ['name' => 'Handball', 'icon' => '🤾', 'type' => 'team'],
    ['name' => 'Water Polo', 'icon' => '🤽', 'type' => 'team'],
    ['name' => 'Beach Volleyball', 'icon' => '🏐', 'type' => 'team'],
    ['name' => 'Futsal', 'icon' => '⚽', 'type' => 'team'],
    ['name' => 'Netball', 'icon' => '🏀', 'type' => 'team'],
    ['name' => 'Gaelic Football', 'icon' => '🏐', 'type' => 'team'],
    ['name' => 'Hurling', 'icon' => '🏏', 'type' => 'team'],
    ['name' => 'Lacrosse', 'icon' => '🥍', 'type' => 'team'],
    ['name' => 'Australian Rules Football', 'icon' => '🏉', 'type' => 'team'],
    ['name' => 'Sepak Takraw', 'icon' => '🏐', 'type' => 'team'],
    ['name' => 'Ultimate Frisbee', 'icon' => '💿', 'type' => 'team'],

    // Racket & String Sports
    ['name' => 'Badminton', 'icon' => '🏸', 'type' => 'both'],
    ['name' => 'Tennis', 'icon' => '🎾', 'type' => 'both'],
    ['name' => 'Table Tennis', 'icon' => '🏓', 'type' => 'both'],
    ['name' => 'Squash', 'icon' => '🎾', 'type' => 'individual'],
    ['name' => 'Pickleball', 'icon' => '🏓', 'type' => 'both'],
    ['name' => 'Padel', 'icon' => '🎾', 'type' => 'both'],
    ['name' => 'Racquetball', 'icon' => '🎾', 'type' => 'individual'],

    // Combat & Martial Arts
    ['name' => 'Boxing', 'icon' => '🥊', 'type' => 'individual'],
    ['name' => 'Wrestling', 'icon' => '🤼', 'type' => 'individual'],
    ['name' => 'Karate', 'icon' => '🥋', 'type' => 'individual'],
    ['name' => 'Judo', 'icon' => '🥋', 'type' => 'individual'],
    ['name' => 'Taekwondo', 'icon' => '🥋', 'type' => 'individual'],
    ['name' => 'Fencing', 'icon' => '🤺', 'type' => 'individual'],
    ['name' => 'Mixed Martial Arts (MMA)', 'icon' => '�', 'type' => 'individual'],
    ['name' => 'Muay Thai', 'icon' => '🥋', 'type' => 'individual'],
    ['name' => 'Kickboxing', 'icon' => '🥊', 'type' => 'individual'],
    ['name' => 'Sumo Wrestling', 'icon' => '�', 'type' => 'individual'],
    ['name' => 'Kung Fu', 'icon' => '🥋', 'type' => 'individual'],
    ['name' => 'Brazilian Jiu-Jitsu', 'icon' => '🥋', 'type' => 'individual'],
    ['name' => 'Kendo', 'icon' => '🤺', 'type' => 'individual'],
    ['name' => 'Kabaddi', 'icon' => '🏃', 'type' => 'team'],
    ['name' => 'Sambo', 'icon' => '🥋', 'type' => 'individual'],

    // Athletics, Track & Field
    ['name' => 'Athletics (General)', 'icon' => '🏃', 'type' => 'individual'],
    ['name' => '100m Sprint', 'icon' => '🏃‍♂️', 'type' => 'individual'],
    ['name' => '200m Sprint', 'icon' => '🏃‍♀️', 'type' => 'individual'],
    ['name' => '400m Dash', 'icon' => '🏃‍♂️', 'type' => 'individual'],
    ['name' => '800m Run', 'icon' => '🏃‍♀️', 'type' => 'individual'],
    ['name' => '1500m Run', 'icon' => '🏃‍♂️', 'type' => 'individual'],
    ['name' => 'Marathon', 'icon' => '🏃‍♀️', 'type' => 'individual'],
    ['name' => 'Relay Race 4x100m', 'icon' => '🏃‍♂️', 'type' => 'team'],
    ['name' => 'Relay Race 4x400m', 'icon' => '🏃‍♀️', 'type' => 'team'],
    ['name' => 'Hurdles', 'icon' => '🏃‍♂️', 'type' => 'individual'],
    ['name' => 'High Jump', 'icon' => '🏃‍♀️', 'type' => 'individual'],
    ['name' => 'Long Jump', 'icon' => '🏃‍♂️', 'type' => 'individual'],
    ['name' => 'Triple Jump', 'icon' => '🏃‍♀️', 'type' => 'individual'],
    ['name' => 'Pole Vault', 'icon' => '🏃‍♂️', 'type' => 'individual'],
    ['name' => 'Shot Put', 'icon' => '☄️', 'type' => 'individual'],
    ['name' => 'Discus Throw', 'icon' => '💿', 'type' => 'individual'],
    ['name' => 'Javelin Throw', 'icon' => '🔱', 'type' => 'individual'],
    ['name' => 'Hammer Throw', 'icon' => '☄️', 'type' => 'individual'],
    ['name' => 'Race Walking', 'icon' => '🏃', 'type' => 'individual'],
    ['name' => 'Cross Country', 'icon' => '🏃', 'type' => 'individual'],

    // Water & Nautical Sports
    ['name' => 'Swimming (Freestyle)', 'icon' => '🏊', 'type' => 'individual'],
    ['name' => 'Swimming (Backstroke)', 'icon' => '🏊‍♂️', 'type' => 'individual'],
    ['name' => 'Swimming (Breaststroke)', 'icon' => '🏊‍♀️', 'type' => 'individual'],
    ['name' => 'Swimming (Butterfly)', 'icon' => '🏊‍♂️', 'type' => 'individual'],
    ['name' => 'Diving', 'icon' => '🤿', 'type' => 'individual'],
    ['name' => 'Synchronized Swimming', 'icon' => '🏊‍♀️', 'type' => 'team'],
    ['name' => 'Rowing', 'icon' => '🚣', 'type' => 'both'],
    ['name' => 'Canoeing', 'icon' => '🚣‍♂️', 'type' => 'individual'],
    ['name' => 'Kayaking', 'icon' => '🚣‍♀️', 'type' => 'individual'],
    ['name' => 'Sailing', 'icon' => '⛵', 'type' => 'both'],
    ['name' => 'Surfing', 'icon' => '🏄', 'type' => 'individual'],
    ['name' => 'Windsurfing', 'icon' => '🏄‍♂️', 'type' => 'individual'],
    ['name' => 'Kitesurfing', 'icon' => '🏄‍♀️', 'type' => 'individual'],
    ['name' => 'Jet Skiing', 'icon' => '🚤', 'type' => 'individual'],
    ['name' => 'Dragon Boat Racing', 'icon' => '🚣', 'type' => 'team'],

    // Indoor, Mind & Precision Sports
    ['name' => 'Chess', 'icon' => '♟️', 'type' => 'individual'],
    ['name' => 'Carrom', 'icon' => '⭕', 'type' => 'both'],
    ['name' => 'Billiards', 'icon' => '🎱', 'type' => 'individual'],
    ['name' => 'Snooker', 'icon' => '🎱', 'type' => 'individual'],
    ['name' => 'Bowling', 'icon' => '🎳', 'type' => 'individual'],
    ['name' => 'Darts', 'icon' => '🎯', 'type' => 'individual'],
    ['name' => 'Archery', 'icon' => '🏹', 'type' => 'individual'],
    ['name' => 'Shooting (Air Rifle)', 'icon' => '🎯', 'type' => 'individual'],
    ['name' => 'Shooting (Skeet)', 'icon' => '🎯', 'type' => 'individual'],
    ['name' => 'Golf', 'icon' => '⛳', 'type' => 'individual'],
    ['name' => 'Bridge', 'icon' => '🃏', 'type' => 'team'],
    ['name' => 'Poker', 'icon' => '🃏', 'type' => 'individual'],
    ['name' => 'E-Sports (League of Legends)', 'icon' => '🎮', 'type' => 'team'],
    ['name' => 'E-Sports (Counter-Strike)', 'icon' => '🎮', 'type' => 'team'],
    ['name' => 'E-Sports (FIFA)', 'icon' => '�', 'type' => 'individual'],

    // Gymnastics, Dance & Fitness
    ['name' => 'Artistic Gymnastics', 'icon' => '🤸', 'type' => 'individual'],
    ['name' => 'Rhythmic Gymnastics', 'icon' => '🤸‍♀️', 'type' => 'individual'],
    ['name' => 'Trampolining', 'icon' => '🤸‍♂️', 'type' => 'individual'],
    ['name' => 'Aerobics', 'icon' => '🧘', 'type' => 'individual'],
    ['name' => 'Yoga', 'icon' => '🧘‍♂️', 'type' => 'individual'],
    ['name' => 'Pilates', 'icon' => '🧘‍♀️', 'type' => 'individual'],
    ['name' => 'Dance Sport (Ballroom)', 'icon' => '💃', 'type' => 'team'],
    ['name' => 'Breakdancing', 'icon' => '💃', 'type' => 'individual'],
    ['name' => 'Cheerleading', 'icon' => '📣', 'type' => 'team'],
    ['name' => 'Bodybuilding', 'icon' => '�️', 'type' => 'individual'],
    ['name' => 'Powerlifting', 'icon' => '�️‍♂️', 'type' => 'individual'],
    ['name' => 'CrossFit', 'icon' => '💪', 'type' => 'individual'],

    // Winter & Extreme Sports
    ['name' => 'Ice Hockey', 'icon' => '🏒', 'type' => 'team'],
    ['name' => 'Figure Skating', 'icon' => '⛸️', 'type' => 'individual'],
    ['name' => 'Speed Skating', 'icon' => '⛸️', 'type' => 'individual'],
    ['name' => 'Skiing (Alpine)', 'icon' => '⛷️', 'type' => 'individual'],
    ['name' => 'Skiing (Cross-Country)', 'icon' => '⛷️', 'type' => 'individual'],
    ['name' => 'Snowboarding', 'icon' => '🏂', 'type' => 'individual'],
    ['name' => 'Curling', 'icon' => '🥌', 'type' => 'team'],
    ['name' => 'Bobsleigh', 'icon' => '🛷', 'type' => 'team'],
    ['name' => 'Cycling (Road)', 'icon' => '🚲', 'type' => 'individual'],
    ['name' => 'Cycling (Mountain)', 'icon' => '🚵', 'type' => 'individual'],
    ['name' => 'Cycling (Track)', 'icon' => '🚲', 'type' => 'individual'],
    ['name' => 'Skateboarding', 'icon' => '🛹', 'type' => 'individual'],
    ['name' => 'BMX', 'icon' => '🚲', 'type' => 'individual'],
    ['name' => 'Rock Climbing', 'icon' => '🧗', 'type' => 'individual'],
    ['name' => 'Mountaineering', 'icon' => '🧗‍♀️', 'type' => 'individual'],
    ['name' => 'Paragliding', 'icon' => '🪂', 'type' => 'individual'],
    ['name' => 'Skydiving', 'icon' => '🪂', 'type' => 'individual'],

    // Others
    ['name' => 'Motorsport (Formula 1)', 'icon' => '🏎️', 'type' => 'individual'],
    ['name' => 'Motorsport (MotoGP)', 'icon' => '�️', 'type' => 'individual'],
    ['name' => 'Horse Racing (Equestrian)', 'icon' => '🏇', 'type' => 'individual'],
    ['name' => 'Polo', 'icon' => '�', 'type' => 'team'],
    ['name' => 'Tug of War', 'icon' => '💪', 'type' => 'team'],
    ['name' => 'Bocce', 'icon' => '🏐', 'type' => 'both'],
    ['name' => 'Billards', 'icon' => '🎱', 'type' => 'individual'],
    ['name' => 'Snooker', 'icon' => '�', 'type' => 'individual'],
];
